### ISSUE TITLE
Failed to compile on OSX Sierra 10.12

### ISSUE THREAD

**Issue by f34nk** [f34nk/tidy_ex#4]
TidyEx failes to compile on OSX Sierra 10.12 because of missing open_memstream.
```
[ 13%] Linking C executable tidy_worker
Undefined symbols for architecture x86_64:
  "_open_memstream", referenced from:
      _eterm_vec_join in eterm_vec.c.o
      _eterm_to_string in eterm_vec.c.o
ld: symbol(s) not found for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
make[2]: *** [tidy_worker] Error 1
make[1]: *** [CMakeFiles/tidy_worker.dir/all] Error 2
make: *** [all] Error 2
```

**Comment by f34nk** [comment]
// memstream functions are conforming to POSIX.1-2008.  These functions are
// not specified in POSIX.1-2001 and are not widely available on other
// systems.
https://www.gnu.org/software/gnulib/manual/html_node/open_005fmemstream.html

**Comment by f34nk** [comment]
Same issue with my other package:
https://github.com/f34nk/modest_ex/issues/21
